apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: maven-java-pipeline-run-
  finalizers:
    - chains.tekton.dev/pipelinerun
  labels:
    tekton.dev/pipeline: maven-java-pipeline
spec:
  params:
    - name: GIT_REPO
      value: "https://github.com/ozyohthree/DO288-apps"
    - name: GIT_REVISION
      value: "pipelines-review-soln"
    - name: MVN_APP_PATH
      value: "apps/pipelines-review/vertx-site"
    - name: DEPLOY_ARTIFACT_NAME
      value: "target/vertx-site-1.0.0-SNAPSHOT-fat.jar"
    - name: DEPLOY_APP_NAME
      value: "vertx-site"
  pipelineRef:
    name: maven-java-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: nfs-storage
          volumeMode: Filesystem
    - name: maven_config
      secret:
        secretName: mvn-settings
