apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-task
spec:
  workspaces:
  - name: source
  - name: maven_config
  params:
  - name: app_path
    description: Path to the application source code in the directory
    type: string
  steps:
    - name: build
    # YOUR WORK HERE
