apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-task
spec:
  workspaces:
  - name: source
    description: Source code will be cloned onto the volume backing source workspace
  - name: maven_config
    description: This workspace will contain the settings.xml as a secret [mvn-settings]
  params:
  - name: app_path
    description: Path to the application source code in the directory
    type: string
  steps:
    - name: build
    # YOUR WORK HERE
