apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: maven-java-pipeline-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]  
  bindings:
    - ref: maven-java-pipeline-tb
  template:
    ref: maven-java-pipeline-tt
