apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: maven-java-pipeline-tb
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-repo-mvn-app-path
    value: $(body.repository.path)  
