apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: nodejs-build-trigger
spec:
  serviceAccountName: pipeline
  # interceptors:
  #   - ref:
  #       name: "github"
  #     params:
  #       - name: "secretRef"
  #         value:
  #           secretName: github-secret
  #           secretKey: secretToken
  #       - name: "eventTypes"
  #         value: ["push"]
  bindings:
    - ref: nodejs-build
  template:
    ref: nodejs-build
